version: '3.7'

services:
    test_db:
        image: postgres:12.1-alpine
        environment:
            POSTGRES_PASSWORD: 'testuser'
            POSTGRES_USER: 'testuser'
        networks:
            - test-network

networks:
    test-network:
