version: '3.7'

services:
    test_db:
        image: postgres:12.1-alpine
        environment:
            POSTGRES_PASSWORD: 'testuser'
            POSTGRES_USER: 'testuser'
        networks:
            - test_network
        container_name: test_db

networks:
    test_network:
        driver: overlay
        name: test_network
