# Generated by Django 2.0.6 on 2018-11-01 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180826_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(verbose_name='transaction date')),
                ('original_description', models.CharField(max_length=255)),
                ('custom_description', models.CharField(blank=True, max_length=255)),
                ('expense', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Category')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Store')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.SubCategory')),
                ('transactionstatus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.TransactionStatus')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='transaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Transaction'),
        ),
    ]
