# Generated by Django 2.0.6 on 2018-07-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180715_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expense',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
