# Generated by Django 2.0.6 on 2018-07-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180715_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='transaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Store'),
        ),
    ]
