# Generated by Django 2.0.6 on 2018-08-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='TransactionStatus',
        ),
    ]
