# Generated by Django 2.1.7 on 2019-03-18 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20190111_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'sub categories'},
        ),
        migrations.AlterModelOptions(
            name='transactionstatus',
            options={'verbose_name_plural': 'transaction statuses'},
        ),
    ]
